### ISSUE TITLE
Dados históricos no csv

### ISSUE THREAD

**Issue by ceciliadolago** [vitorbaptista/google-covid19-mobility-reports#2]
Olá, seria possível que a base em CSV carregasse em si não somente a última data de atualização, mas também acumulasse as datas antigas? Assim teríamos um acompanhamento.

**Comment by vitorbaptista** [comment]
Oi @ceciliadolago, é isso mesmo que vai acontecer. Assim que o Google lançar os dados atualizados, eles aparecerão no CSV.

Também acabei de descobrir o https://github.com/pastelsky/covid-19-mobility-tracker, que extraiu os dados das imagens dos gráficos. Assim eles já têm dados desde Fevereiro/2020. Por exemplo, os dados do Brasil estão em https://github.com/pastelsky/covid-19-mobility-tracker/tree/master/output/BR.
