### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [vitorbaptista/google-covid19-mobility-reports#3]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/FCCEPS
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by vitorbaptista** [comment]
Hi @reeshmabijosh, thanks for getting this data in. The CoronaWhy project looks great!

However, this dataset isn't useful anymore. In the beginning, Google's data was only available in PDFs, which led me to build this. They started publishing the data as CSVs, even more than what I was able to extract from the PDFs. So I'd suggest pointing people to https://www.google.com/covid19/mobility/ instead, potentially replicating that dataset in your repository (if it isn't in already).
